import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SessionProvider from "@/contexts/session";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Paytm Clone",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider>
                    <Header />
                    <div className="mt-[92px]">{children}</div>
                    <Footer />
                </SessionProvider>
				<Toaster position="bottom-center" containerClassName="text-sm" />
            </body>
        </html>
    );
}
